import { Outfit } from 'next/font/google'
import "./globals.css";
const outfit = Outfit({ subsets: ['latin'] });
import { ClerkProvider, SignedIn, SignedOut, SignIn } from '@clerk/nextjs';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body
        className={outfit.className}
      >
        <ClerkProvider>
          <SignedOut>
            <div className="min-h-screen min-w-screen flex justify-center items-center">
              <SignIn routing="hash" />
            </div>
          </SignedOut>
         <SignedIn>
            {children}
          </SignedIn>

        </ClerkProvider>
      </body>
    </html>
  );
}
